# Generated by Django 5.2.5 on 2025-10-07 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DicomMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(blank=True, max_length=255)),
                ('patient_id', models.CharField(blank=True, max_length=255)),
                ('patient_sex', models.CharField(blank=True, max_length=10)),
                ('patient_birth_date', models.CharField(blank=True, max_length=20)),
                ('patient_age', models.CharField(blank=True, max_length=20)),
                ('study_instance_uid', models.CharField(blank=True, max_length=255)),
                ('study_id', models.CharField(blank=True, max_length=255)),
                ('study_date', models.CharField(blank=True, max_length=50)),
                ('study_time', models.CharField(blank=True, max_length=50)),
                ('accession_number', models.CharField(blank=True, max_length=255)),
                ('study_description', models.TextField(blank=True)),
                ('series_instance_uid', models.CharField(blank=True, max_length=255)),
                ('series_number', models.CharField(blank=True, max_length=50)),
                ('series_description', models.TextField(blank=True)),
                ('modality', models.CharField(blank=True, max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('institution_name', models.CharField(blank=True, max_length=255)),
                ('body_part_examined', models.CharField(blank=True, max_length=255)),
                ('protocol_name', models.CharField(blank=True, max_length=255)),
                ('kvp', models.CharField(blank=True, max_length=50)),
                ('slice_thickness', models.CharField(blank=True, max_length=50)),
                ('pixel_spacing', models.CharField(blank=True, max_length=50)),
                ('rows', models.CharField(blank=True, max_length=50)),
                ('columns', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dicom_metadata', to='filemanager.file')),
            ],
        ),
    ]
